### ISSUE TITLE
What about the RGB LED?

### ISSUE THREAD

**Issue by snobu** [DevKitExamples/DevKitState#2]
This is a fancy but very practical demo, i like it. It could be improved by writing logic to independently turn the RGB LED on/off.

Something along these lines:

```c
RGB_LED rgbLed;
...

void parseTwinMessage(DEVICE_TWIN_UPDATE_STATE updateState, const char *message)
{
...

    if (userLEDState) {
      // Light up RGB LED
      rgbLed.setColor(255, 0, 60); // magenta
    }
    else {
      rgbLed.turnOff();
    }

...
}
```
Better yet, the color should be controlled by device twin.. although looking at that `rgbLed.setColor()` it's not immediately clear how that could be implemented.. any ideas? Can you call a function with arguments on the device via its twin? e.g. `UpdateRGBLed(int r, int g, int b)`

Of course the vue.js frontend needs to implement all this as well, the twin JSON definition and Azure Function most probably need some minor changes as well. Do you take pull requests?

**Comment by Sneezry** [comment]
I have added RGB LED support, please try the latest code and free feel to post any feedback :-)

**Comment by snobu** [comment]
Really nice job, the color sliders are so much win they'll probably clone them for CSI Cyber or something.
I've added a handful of eye candy, check new PRs :)

**Comment by Sneezry** [comment]
Nice job!

**Comment by snobu** [comment]
Added in https://github.com/DevKitExamples/DevKitState/commit/e102a7911172090ab388caf0e28444b35b8d2a16 and perfected later on :)
