### ISSUE TITLE
Reference issues in azure function

### ISSUE THREAD

**Issue by ps-sagar** [DevKitExamples/DevKitState#9]
Not able to build azure function .

I have just  started working on the dev kit.  followed the provided instructions and facing issue with references in Azure function run.csx file.
![image](https://user-images.githubusercontent.com/39048592/40529730-c832a8e0-6013-11e8-9542-e2e5229b3a42.png)

**Comment by snobu** [comment]
You need a few extras to author C# (.NET Core) functions in VSCode. See this guide - 
https://github.com/Microsoft/vscode-azurefunctions#c

That being said, if you can live with those red squiggles, just publish the function to Azure via the Task menu, it will work.

**Comment by Sneezry** [comment]
@snobu Cool! PR is welcome :-D

**Comment by hackerxzx** [comment]
Hi! @snobu @ps-sagar  @Sneezry 

Got the same problem, tried following the procedure and uploading the function but it wont work.
Here are some captures of the errors i get.

![captura](https://user-images.githubusercontent.com/40066016/41164831-ba2af254-6b01-11e8-837f-99bfcee98701.PNG)

![captura2](https://user-images.githubusercontent.com/40066016/41164845-bffcab1e-6b01-11e8-8ef4-ae206286c92a.PNG)

**Comment by snobu** [comment]
Two things, make sure project.json is in there alongside run.csx. What's the log/error window telling you?

**Comment by snobu** [comment]
And check that you're on 1.x runtime not on beta/v2.

**Comment by hackerxzx** [comment]
Files:
![captura](https://user-images.githubusercontent.com/40066016/41170072-88d8b484-6b10-11e8-9c4b-4eb427d9ad79.PNG)

csproj:
![captura4](https://user-images.githubusercontent.com/40066016/41170089-927b2bb6-6b10-11e8-8f15-ddccf6995399.PNG)

Log:
![captura2](https://user-images.githubusercontent.com/40066016/41170150-bcf5cf40-6b10-11e8-8d91-35cb90eb1bb2.PNG)

Runtime:
![captura3](https://user-images.githubusercontent.com/40066016/41170111-a51a5bf2-6b10-11e8-8a11-09d9d3ca375d.PNG)

It´s not finding the Nuget Packages...

**Comment by hackerxzx** [comment]
Fixed it! Used the original project.json instead of csproj.

**Comment by snobu** [comment]
You sure you have the right branch?
https://github.com/DevKitExamples/DevKitState/tree/master/azureFunction/devkit-state

**Comment by snobu** [comment]
Great, thanks for reporting back!
